add test for `get_output_model_name_string`
ihmeuw/vivarium pull request #221
Opened 2022-08-16 20:24 UTC by mattkappel

## add test for `get_output_model_name_string`

### Description
- *Category*: test
- *JIRA issue*:  [MIC-3317](https://jira.ihme.washington.edu/browse/MIC-3317)

#### Changes
- Adds a test file for interface/utilities, specifically for the `get_output_model_name_string` method used by `psimulate` and `simulate` commands.

### Testing
Pytest runs this test successfully.

2022-08-16 21:15 UTC, albrja approved these changes

2022-08-17 17:02 UTC, rmudambi requested changes

2022-08-17 17:02 UTC, rmudambi commented on tests/interface/test_utilities.py
> +def test_get_output_model_name_string(tmp_path):
It's better form to use `@pytest.mark.parametrize` to capture each of these three cases. See `test_artifact` line 526 for an example.

2022-08-18 16:41 UTC, stevebachmeier approved these changes

2022-08-18 19:59 UTC, rmudambi approved these changes

2022-08-18 21:02 UTC, merged