Update randomness.choice
ihmeuw/vivarium pull request #261
Opened 2023-01-14 00:52 UTC by hussain-jafari

## Update randomness.choice 

### Description=
- *Category*: feature
- *JIRA issue*: [MIC-3290](https://jira.ihme.washington.edu/browse/MIC-3290)

Warn user if they are passing in a large amount of data which will have a significant impact on memory and performance. Add checks to make sure the passed probability array is the right shape. Use faster method to get choice indexes when probabilities are not specified. Use binary search method on cdfs to get choice indexes when probability is specified. Add test to make sure results are the same with implicit probabilities and explicit uniform probabilities. Update docstring.  

### Testing
Ran test_choice and new test. Checked interactively that old code and new code gave same results with no probability specified, and with uniform and non-uniform 1-d and 2-d probabilities (5 cases total).

2023-01-14 01:35 UTC, rmudambi requested changes
Since we're here, we should add a 2-d weights test

2023-01-14 01:35 UTC, rmudambi commented on src/vivarium/framework/randomness.py
> +        warnings.warn(
Should use the `loguru` `logger`. That is how we do logging elsewhere in vivarium

2023-01-14 01:35 UTC, rmudambi commented on src/vivarium/framework/randomness.py
> +                    f"You've provided {len(p)} probabilities which is inconsistent"
Missing a space at the end of the line

2023-01-14 01:35 UTC, rmudambi commented on src/vivarium/framework/randomness.py
> +            explicitly might lead to high memory usage and/or performance slowdown.
You need to add a docstring for the new `large_N` parameter.

2023-01-14 01:35 UTC, rmudambi commented on tests/framework/test_randomness.py
> +    explicit_choices = randomness.choice(index, choices, p=[1] * len(choices))
I don't understand what you're testing here.

2023-01-17 21:49 UTC, stevebachmeier commented on src/vivarium/framework/randomness.py
> +            "You are passing a large amount of data to the choice function with explicit probabilities."
Consider making an f-string w/ {key} in the message for easier debugging

2023-05-03 21:40 UTC, closed without merging