gather_results empty data bugfix
ihmeuw/vivarium pull request #279
Opened 2023-02-23 22:11 UTC by hussain-jafari

## gather_results empty data bugfix

### Description
- *Category*: bugfix
- *JIRA issue*: [MIC-3840](https://jira.ihme.washington.edu/browse/MIC-3840)

When we filter to an empty population in gather_results, the output of our groupby -> aggregate is an empty dataframe. Vivarium tries to convert this to a Series using squeeze and errors out if it's not a Series. However, an empty dataframe that is squeezed is still a dataframe.

### Testing
Added test with filter that would lead to an empty dataframe. Checked that previous code failed test and that updated code passed.

2023-02-23 23:43 UTC, rmudambi requested changes

2023-02-23 23:43 UTC, rmudambi commented on tests/framework/results/test_context.py
> +        ("wizard_count", "house=='Durmstrang'", None, len, ["house", "familiar"], 4),
This test passes, but it doesn't make any sense. There aren't 4 member of Durmstrang in each stratification group. There are 0, but `gather_results()` returns an empty dict, which means that any assertion will pass. Our test should be that the returned dict is empty.

2023-02-24 01:20 UTC, rmudambi approved these changes

2023-02-24 02:27 UTC, mattkappel approved these changes

2023-02-24 17:20 UTC, merged