Albrja/mic 5383/add-number-steps-method
ihmeuw/vivarium pull request #493
Opened 2024-10-04 23:22 UTC by albrja

## Albrja/mic 5383/add-number-steps-method

### Adds method to SimulationContext to retreive number of steps
- *Category*: Feature
- *JIRA issue*: https://jira.ihme.washington.edu/browse/MIC-5383

### Changes and notes
-adds method to InteractiveContext

### Testing

2024-10-04 23:32 UTC, rmudambi approved these changes
Let's go ahead with this for now to unblock the simulation model, but this solution isn't quite general enough to support all types of clocks, so we should update it later. 

Can you create another ticket to deal with that and put it in the backlog?

2024-10-04 23:32 UTC, rmudambi commented on CHANGELOG.rst
> +  - Add method to InteractiveContext to get number of simulation steps
This should read SimulationContext, not InteractiveContext

2024-10-04 23:32 UTC, rmudambi commented on src/vivarium/framework/engine.py
> +                "'End' and 'step_size' or 'simulation_events' are required."
Nit: `End` -> `end`

2024-10-04 23:33 UTC, rmudambi requested changes

2024-10-04 23:33 UTC, rmudambi commented on src/vivarium/framework/engine.py
> +    def get_number_of_steps(self, start_time: pd.Timestamp) -> int:
This method shouldn't take any arguments. It should be able to figure out the start time on its own.

2024-10-07 15:54 UTC, stevebachmeier reviewed
good to go once you sort out the start_time issue

2024-10-07 15:54 UTC, stevebachmeier commented on src/vivarium/framework/engine.py
> +                "'End' and 'step_size' or 'simulation_events' are required."
nit: ambiguous. Maybe "Time configuration is incomplete. Either 'end' and 'step_size' values or a 'simulation_events' list are required."

2024-10-07 15:54 UTC, stevebachmeier commented on src/vivarium/framework/engine.py
> +        elif "simulation_events" in time_config:
Should we handle the event where `simulation_events` AND end time or step size is provided (probably a raise?)?

2024-10-07 21:39 UTC, rmudambi commented on tests/framework/test_time.py
> +        (23, "SimpleClock"),
The config of `SimpleClock` looks like this: 
```python
CONFIGURATION_DEFAULTS = {
        "time": {
            "start": 0,
            "end": 100,
            "step_size": 1,
            "standard_step_size": None,
        }
    }
```
Configuring it like this doesn't seem correct

2024-10-07 21:52 UTC, rmudambi approved these changes

2024-10-07 21:54 UTC, stevebachmeier approved these changes

2024-10-07 21:56 UTC, merged